name: AxGraves
version: '${project.version}'
main: com.artillexstudios.axgraves.AxGraves
api-version: '1.20'
folia-supported: true
softdepend: [WorldGuard]

permissions:
  axgraves.help:
    default: true
  axgraves.reload:
    default: op
  axgraves.list:
    default: true
  axgraves.list.other:
    default: op
  axgraves.tp:
    default: op
  axgraves.tp.bypass:
    default: op
  axgraves.allowgraves:
    default: true
  axgraves.limit.1:
    default: false
  grave.vip1:
    default: false
    description: "VIP level 1 - Extended grave despawn time (5 minutes)"
  grave.vip2:
    default: false
    description: "VIP level 2 - Extended grave despawn time (10 minutes)"